### PR TITLE
add state for no access

### PR DESCRIPTION
**Pull request by ryelo**
## What
This shows an empty state when a user is not an org admin

## Jira
https://projects.engineering.redhat.com/browse/RHCLOUD-4519

## Mocks
https://marvelapp.com/d76d9ja/screen/66345478/handoff

## Screenshots
Screen Shot 2020-02-19 at 12 05 41 PM
Screen Shot 2020-02-19 at 12 05 23 PM

### CODE REVIEW

**Comment by ryelo** [comment]
@mmenestr

**Comment by mmenestr** [comment]
Question: did you do one version for if they click into this page from another page, and another version for if they copy paste the URL to get here directly?
(The only difference would be what the button says)

**Comment by karelhala** [comment]
@mmenestr yes, if user pasted the URL in there he'd get `Go to landing page`, but if they have any history in crc they'd see `Return to previous page`

**Comment by ryelo** [comment]
My bad. Totally didn't upload that screenshot. Posting here and in the initial comment!

Screen Shot 2020-02-19 at 10 59 37 AM
Screen Shot 2020-02-18 at 2 25 35 PM

**Comment by mmenestr** [comment]
Looks great! Just one thing, I am now re-considering the Header text.
I want it to say "You do not have permissions to view and manage User access" instead of "You do not have permissions to User access" Sorry for the last minute change, just doesn't sound right now that i'm seeing it again :)

**Comment by ryelo** [comment]
@mmenestr 
Screen Shot 2020-02-19 at 12 05 41 PM
Screen Shot 2020-02-19 at 12 05 23 PM

**Comment by karelhala** [comment]
@ryelo looks like you forgot to update the code, once updated it is ready to :shipit:

**Comment by ryelo** [comment]
HA that's embarrassing

**Comment by ryelo** [comment]
Putting on hold until content gets back to us!

**Comment by mmenestr** [comment]
Update: the text should be "You do not have permissions to view or manage User access"
with the only difference with what you have now being the "OR" instead of the "AND"!

Also the header text should not go beyond a width of 536px. So if it has to become two lines because of that, that's fine!

**Comment by ryelo** [comment]
@mmenestr updated! Max width of the title is 536px

Screen Shot 2020-02-20 at 12 51 01 PM

**Comment by ryelo** [comment]
jk updating to 540px to fit on one line

Screen Shot 2020-02-20 at 1 23 50 PM

**Comment by mmenestr** [comment]
Note: making an exception here to make the width 540px instead of max of 536px so that everything can fit in one line (because it looks bad with just one extra word below).

Good to merge on my end!! Thank you rlong

**Pull request merged**
