### PR TITLE
Add "Add Service Account" to the Create Group Wizard

### PR DESCRIPTION
**Pull request by fhlavac**
### Description

Added "Add Service Account" step to the Create Group Wizard + progress bar at the end of the flow displaying the process of creation.

[RHCLOUD-29420](https://issues.redhat.com/browse/RHCLOUD-29420)

---

#### Before:
image

#### After:
Snímek obrazovky 2024-03-26 v 16 37 04

Snímek obrazovky 2024-03-26 v 16 37 13

Snímek obrazovky 2024-03-28 v 16 02 32

Snímek obrazovky 2024-03-28 v 16 03 12

Snímek obrazovky 2024-03-26 v 16 38 42

Snímek obrazovky 2024-03-26 v 16 42 37

---

### Checklist ☑️
- [x] PR only fixes one issue or story 
- [x] Change reviewed for extraneous code 
- [x] UI best practices adhered to 
- [x] Commits squashed and meaningfully named 
- [x] All PR checks pass locally (build, lint, test, E2E)

##
- [x] _(Optional) QE: Needs QE attention (OUIA changed, perceived impact to tests, no test coverage)_
- [x] _(Optional) QE: Has been mentioned_
- [x] _(Optional) UX: Needs UX attention (end user UX modified, missing designs)_
- [x] _(Optional) UX: Has been mentioned_
##

### CODE REVIEW

**Comment by InsaneZein** [comment]
To me, the title and progress bar look a little off, because they're not centered on top of each other. Could we center them and move the `creating a service accounts` below it?

**Comment by fhlavac** [comment]
@InsaneZein that's what PF does by default. UX approved it that way, but I'll try to make it a bit nicer.

**Pull request merged**
