### PR TITLE
Update prod beta with master changes

### PR DESCRIPTION
**Pull request by Hyperkid123**
part of: https://issues.redhat.com/browse/RHCLOUD-10977

wait for: https://github.com/RedHatInsights/insights-rbac-ui/pull/627

### CODE REVIEW

**Review by karelhala — APPROVED** [review]

**Comment by Hyperkid123** [comment]
@john-dupuy can trigger a test run on this PR? It is basically a master with a create roles beta flag.

**Comment by john-dupuy** [comment]
With #627, and once the BE changes are pushed to prod, this LGTM.

**Comment by Hyperkid123** [comment]
@john-dupuy the PR fixing the custom role buttons and the toolbar dropdown has been merged. Can we try another test run?

**Review by john-dupuy — APPROVED** [review]
Testing this PR out manually and with automation -- it looks good to me. I found one small bug in MUA that isn't a result of this PR (it is also present in qa-beta).

**Review by ryelo — APPROVED** [review]

**Comment by Hyperkid123** [comment]
Ok I will merge this one. We can wait a bit with the prod stable update.

**Pull request merged**
