### PR TITLE
Update file names to match convention

### PR DESCRIPTION
**Pull request by lgalis**
Update file names to match convention.

Should be merged after #25

### CODE REVIEW

**Comment by lgalis** [comment]
@Hyperkid123  - please review

**Comment by Hyperkid123** [comment]
@lgalis @gmcculloug this change seem ok but when i run the rbac UI locally i am getting redirected to catalog again. Are you aware of any possible breaking changes on our or platform side?

**Comment by Hyperkid123** [comment]
@lgalis works. I believe that there is an outdated version PF. Can you update it (not in this PR)?

**Comment by lgalis** [comment]
@Hyperkid123 - thank you for the review - I'll update the PF4 version

**Pull request merged**
