### PR TITLE
Add info about inactive users

### PR DESCRIPTION
**Pull request by karelhala**
Screenshot from 2020-04-17 10-36-07
Screenshot from 2020-04-17 10-36-37
Screenshot from 2020-04-17 10-37-01

### CODE REVIEW

**Comment by karelhala** [comment]
ping @mmenestr

**Comment by john-dupuy** [comment]
@karelhala I have some concerns that this might break the widget we use to represent a `Table` in c.rh.c. When we lookup a user in the table we match against the username text. I would have to check to be sure, but now the username text might also include that "Active/Inactive" text before the username. 

Apologies if this was discussed on ticket @mmenestr, but is there any issue UX wise if the chip/label is in a separate (untitled) column? If so, I'm sure I can figure out a workaround.

**Comment by karelhala** [comment]
@john-dupuy yeah, you are right, now part of username is Active/Inactive label. Mhh I could move the label to specific column before the username if that would help.

**Comment by mmenestr** [comment]
No issue with moving the label to another separate column! I would prefer that based on what you're saying :) 

Also 2 other notes I have:
1. **The description in the user page should be "These are all the users in your Red Hat organization. To add new users or manage existing users, go to your user management list."** It's just a little longer than the ones in the modals.

2. The disabled text color seems a little too light? But maybe it's the screenshot. Could you use --pf-global--disabled-color--100 if not already?

**Comment by karelhala** [comment]
> No issue with moving the label to another separate column! I would prefer that based on what you're saying :)
> 
> Also 2 other notes I have:
> 
> 1. **The description in the user page should be "These are all the users in your Red Hat organization. To add new users or manage existing users, go to your user management list."** It's just a little longer than the ones in the modals.

Sure thing!

> 2. The disabled text color seems a little too light? But maybe it's the screenshot. Could you use --pf-global--disabled-color--100 if not already?

I've used `pf-global--disabled-color--100` for the inactive label and `pf-global--disabled-color--200` for the color of inactive row.

**Comment by john-dupuy** [comment]
Yup, in a separate column there'd be no problem for our widget at all!

**Comment by mmenestr** [comment]
The color of the row text is too light! Could you use --pf-global--disabled-color--100 instead so that the username, name etc are more readable?

**Comment by karelhala** [comment]
Oh you mean the color of the text in a row, sure thing! I'll update it to use `-100`.

**Comment by karelhala** [comment]
This is how it looks like with lighter color
Screenshot from 2020-04-17 10-15-45

**Comment by karelhala** [comment]
@mmenestr screenshots updated. I've added table cell header for the Active/Inactive part so users know what it means.

**Comment by mmenestr** [comment]
Ok also LGTM! Thanks Karel!

**Pull request merged**
