### PR TITLE
Change add roles to group modal header & description

### PR DESCRIPTION
**Pull request by tahmidefaz**
Jira: https://projects.engineering.redhat.com/browse/RHCLOUD-4445

**Screenshot**
image

### CODE REVIEW

**Comment by tahmidefaz** [comment]
Ping! @mmenestr

**Comment by mmenestr** [comment]
@tahmidefaz Now that I see the double group when the group name has the word "group" in it, do you mind changing the description to say "This role list has been **filtered** to **only show roles** that **not currently** in ___**group name**____"

**Comment by tahmidefaz** [comment]
@mmenestr Done! How does it look now?

image

**Comment by mmenestr** [comment]
@tahmidefaz perfect thank you!!

**Pull request merged**
