### PR TITLE
Sync prod stable with latest changes.

### PR DESCRIPTION
**Pull request by Hyperkid123**
part of: https://issues.redhat.com/browse/RHCLOUD-10977

wait for: https://github.com/RedHatInsights/insights-rbac-ui/pull/627

### CODE REVIEW

**Review by karelhala — APPROVED** [review]

**Comment by Hyperkid123** [comment]
This PR should be ready after we include this: https://github.com/RedHatInsights/insights-rbac-ui/pull/632

Fixes the last couple of issues affecting the current master branch.

**Comment by Hyperkid123** [comment]
This is now ready for merge. Includes all the changes and bug fixes already applied in prod-beta branch.

**Comment by karelhala** [comment]
Codewise looks good, @Hyperkid123 let's merge it on monday.

@john-dupuy mind taking this one for a spin and running the tests on it? It should be same as what is in `prod-beta` so I don't think we have to be strict on it. I've also created a tag in case we'd find anything broken so we have a point in time to come back to.

**Comment by Hyperkid123** [comment]
@karelhala we have found out that there are still some beta flags for MUA. Mua is also only showing on beta in the left nav and chrome has different settings links on beta/none-beta. @ryelo will address these issues.

**Comment by ryelo** [comment]
All of the PRs have been opened for the other issues. If you want to sync this one with what is on master, that should address the issues. When that is merged, feel free to merge the CSC and chrome ones too.

**Comment by Hyperkid123** [comment]
@ryelo I will create additional PR with your changes. All these commits make it a bit messy while rebasing.

**Comment by Hyperkid123** [comment]
WRONG BRANCH!

**Pull request merged**
