### PR TITLE
adjust ext link icon

### PR DESCRIPTION
**Pull request by epwinchell**
Jira: https://issues.redhat.com/browse/RHCLOUD-9548

This PR moves the period after the icon.

Follow-up to: https://github.com/RedHatInsights/insights-rbac-ui/pull/511

Screen Shot 2020-10-07 at 10 09 43 AM

Screen Shot 2020-10-07 at 10 04 04 AM

### CODE REVIEW

**Review by karelhala — APPROVED** [review]

**Comment by karelhala** [comment]
@mmenestr let's loop you in here as well.

**Comment by mmenestr** [comment]
Could just make the period part of the <p> text, and not part of the link, so that it's black and isn't as far away from the link?

**Comment by epwinchell** [comment]
> Could just make the period part of the text, and not part of the link, so that it's black and isn't as far away from the link?
@mmenestr The screenshot's updated with the space and link removed.

**Comment by mmenestr** [comment]
Looks great, thank you!!

**Review by Hyperkid123 — APPROVED** [review]

**Pull request merged**
