### PR TITLE
Active users

### PR DESCRIPTION
**Pull request by karelhala**
Screenshot from 2020-04-09 10-06-02
Screenshot from 2020-04-09 10-06-13
Screenshot from 2020-04-09 10-06-28

### CODE REVIEW

**Comment by karelhala** [comment]
ping @mmenestr

**Comment by rvsia** [comment]
Code looks solid, however I have one little notice, it's basically the same text and link on three places (except the 'View' vs 'see' difference :D). It could be just one very little component - the maintenance/testing of the link will be easier.

**Comment by karelhala** [comment]
@rvsia yeah, good point! Added shared component.

**Comment by mmenestr** [comment]
Looks great! Do all the 'user management page' links correctly link to: [](https://www.redhat.com/wapps/ugc/protected/usermgt/userList.html?extIdCarryOver=true&sc_cid=701f2000001Css0AAC) ?

**Comment by mmenestr** [comment]
Just saw this issue though.. https://projects.engineering.redhat.com/browse/RHCLOUD-5157. might not want to show those descriptions if they're not accurate. In other words, since the table can't currently be filtered to show only active users, I don't want to push that description yet. 

The filters are good to go though.

**Pull request merged**
