### PR TITLE
Update categories

### PR DESCRIPTION
**Pull request by Hyperkid123**
### Changes
- update FEC webpack config
- fixed height of the content (it was showing double scrollbar)
- update bundle categories

jira: https://issues.redhat.com/browse/RHCLOUD-13338

Other than that, no changes, everything works the same as before

~~@ryelo I got a question about the application services tile. Should we create an exception and show it to every user or do we want to keep it hidden until application services have entitlements?~~

### Application services
screenshot-ci foo redhat com_1337-2021 04 13-16_05_49

### Openshift alert

screenshot-ci foo redhat com_1337-2021 04 13-15_24_45

cc @beccaglass

### CODE REVIEW

**Comment by beccaglass** [comment]
@Hyperkid123 looks great! A couple small things:

1) Can we get rid of the title above the cards (Your org's subscriptions) ?
2) Change the description under the 'My User Access' header per the mocks: https://marvelapp.com/prototype/11gc312j/screen/78113211

Thank you!

**Comment by Hyperkid123** [comment]
Will do

**Review by karelhala — APPROVED** [review]

**Comment by Hyperkid123** [comment]
@beccaglass

There it is

screenshot-ci foo redhat com_1337-2021 04 14-09_03_53

**Review by PanSpagetka — APPROVED** [review]

**Comment by beccaglass** [comment]
@Hyperkid123 beautiful!!

**Pull request merged**
