### PR TITLE
Add filter for roles in group

### PR DESCRIPTION
**Pull request by karelhala**
### Filtering by multiple fields
Screenshot from 2020-02-20 16-09-20
### Revert of filtering in permissions
Screenshot from 2020-02-20 16-10-07

### CODE REVIEW

**Comment by karelhala** [comment]
@mmenestr this is the updated filter, based on your suggestions from https://github.com/RedHatInsights/insights-rbac-ui/pull/172#issuecomment-589087133

**Comment by mmenestr** [comment]
Last thing - the name attribute is the one that shows up by default right? like if the user didn't touch the filter at all, and is just coming onto the page for the first time, they would see "Name" as the attribute, and would have to click into it to then see "Description" correct?

**Comment by karelhala** [comment]
@mmenestr yup, this is how it looks like
Screenshot from 2020-02-20 16-45-38

**Comment by mmenestr** [comment]
Great! It's good to go then, thank you!!

**Pull request merged**
